import type { SiteData } from "./types";

export const fallbackSiteData: SiteData = {
  profile: {
    name: "Fernando Luna",
    role: "Desarrollador y creador de soluciones digitales",
    tagline: "Construyo software claro, documentación útil y experiencias web con intención.",
    location: "España",
    email: "hola@fernandoluna.dev",
    avatarAlt: "Retrato de Fernando Luna en una esfera de cristal",
    links: [
      { label: "GitHub", href: "https://github.com/", kind: "github" },
      { label: "LinkedIn", href: "https://www.linkedin.com/", kind: "linkedin" },
      { label: "Email", href: "mailto:hola@fernandoluna.dev", kind: "mail" },
    ],
    highlights: [
      "Arquitectura front/back separada",
      "Documentación técnica accesible",
      "Productos web mantenibles",
    ],
  },
  cv: {
    summary:
      "Perfil técnico orientado a crear herramientas web, automatizaciones y documentación que ayudan a equipos y usuarios a trabajar con menos fricción.",
    experience: [
      {
        period: "2024 - Actualidad",
        title: "Constructor de productos web",
        company: "Fernando Luna",
        description:
          "Diseño y desarrollo de interfaces, APIs y sistemas de documentación para proyectos propios y clientes.",
      },
      {
        period: "2022 - 2024",
        title: "Desarrollador full-stack",
        company: "Proyectos independientes",
        description:
          "Integración de frontend, backend y automatizaciones para portales, paneles internos y webs de contenido.",
      },
    ],
    skills: [
      "React",
      "TypeScript",
      "Python",
      "APIs REST",
      "Documentación",
      "Automatización",
      "Diseño de producto",
      "Accesibilidad",
    ],
    education: [
      {
        title: "Aprendizaje continuo en ingeniería web",
        detail:
          "Frontend moderno, backend Python, documentación técnica y herramientas de IA aplicadas al desarrollo.",
      },
    ],
  },
  projects: [
    {
      name: "Portal Fernando Luna",
      category: "Marca personal",
      summary: "Centro visual para CV, proyectos, publicaciones y documentación.",
      status: "En construcción",
      stack: ["React", "Vite", "Python"],
      href: "https://fernandoluna.dev",
      featured: true,
    },
    {
      name: "Biblioteca de documentación",
      category: "Docs",
      summary: "Webs técnicas organizadas por guías, decisiones y notas de implementación.",
      status: "Diseño",
      stack: ["Markdown", "Static site", "Search"],
      href: "https://docs.fernandoluna.dev",
      featured: true,
    },
    {
      name: "Laboratorio de automatizaciones",
      category: "Herramientas",
      summary: "Pequeñas utilidades para reducir trabajo repetitivo en proyectos personales.",
      status: "Activo",
      stack: ["Python", "APIs", "Scripts"],
      href: "https://lab.fernandoluna.dev",
      featured: false,
    },
  ],
  posts: [
    {
      title: "Cómo estoy construyendo mi portal personal",
      date: "2026-05-19",
      excerpt:
        "Notas sobre arquitectura separada, diseño orbital e integración progresiva de contenido real.",
      href: "#",
    },
    {
      title: "Qué debe tener una buena documentación técnica",
      date: "2026-05-10",
      excerpt: "Criterios prácticos para que una guía sea fácil de mantener y útil cuando hay prisa.",
      href: "#",
    },
  ],
  docs: [
    {
      title: "Guías de desarrollo",
      description: "Patrones, decisiones y comandos recurrentes para mis proyectos.",
      href: "https://docs.fernandoluna.dev/guias",
    },
    {
      title: "Bitácora técnica",
      description: "Notas cortas sobre problemas resueltos y aprendizajes reutilizables.",
      href: "https://docs.fernandoluna.dev/bitacora",
    },
    {
      title: "Recursos públicos",
      description: "Plantillas, snippets y referencias que puedo compartir.",
      href: "https://docs.fernandoluna.dev/recursos",
    },
  ],
  sections: [
    {
      id: "cv",
      route: "cv",
      label: "CV",
      eyebrow: "Trayectoria",
      title: "CV vivo",
      description: "Experiencia, capacidades y foco profesional.",
      iconKey: "briefcase",
      orbit: "inner",
      angle: -90,
      order: 10,
      visibleFrom: null,
      visibleUntil: null,
      enabled: true,
    },
    {
      id: "projects",
      route: "projects",
      label: "Proyectos",
      eyebrow: "Trabajo",
      title: "Proyectos visibles",
      description: "Productos, laboratorios y webs que puedo enseÃ±ar.",
      iconKey: "code",
      orbit: "inner",
      angle: 0,
      order: 20,
      visibleFrom: null,
      visibleUntil: null,
      enabled: true,
    },
    {
      id: "personal",
      route: "personal",
      label: "Personal",
      eyebrow: "Publicaciones",
      title: "Notas personales",
      description: "Espacio para publicar ideas, avances y aprendizajes.",
      iconKey: "user",
      orbit: "inner",
      angle: 90,
      order: 30,
      visibleFrom: null,
      visibleUntil: null,
      enabled: true,
    },
    {
      id: "docs",
      route: "docs",
      label: "Docs",
      eyebrow: "Biblioteca",
      title: "DocumentaciÃ³n",
      description: "Accesos a guÃ­as, recursos y webs tÃ©cnicas.",
      iconKey: "book",
      orbit: "inner",
      angle: 180,
      order: 40,
      visibleFrom: null,
      visibleUntil: null,
      enabled: true,
    },
  ],
  sectionItems: [
    {
      id: "cv-summary",
      sectionId: "cv",
      kind: "card",
      kicker: "Perfil",
      title: "Resumen profesional",
      meta: null,
      description:
        "Perfil tÃ©cnico orientado a crear herramientas web, automatizaciones y documentaciÃ³n que ayudan a equipos y usuarios a trabajar con menos fricciÃ³n.",
      href: null,
      tags: [
        "React",
        "TypeScript",
        "Python",
        "APIs REST",
        "DocumentaciÃ³n",
        "AutomatizaciÃ³n",
        "DiseÃ±o de producto",
        "Accesibilidad",
      ],
      iconKey: "briefcase",
      order: 10,
      visibleFrom: null,
      visibleUntil: null,
      featured: false,
    },
    {
      id: "experience-1",
      sectionId: "cv",
      kind: "experience",
      kicker: "2024 - Actualidad",
      title: "Constructor de productos web",
      meta: "Fernando Luna",
      description:
        "DiseÃ±o y desarrollo de interfaces, APIs y sistemas de documentaciÃ³n para proyectos propios y clientes.",
      href: null,
      tags: [],
      iconKey: "briefcase",
      order: 11,
      visibleFrom: null,
      visibleUntil: null,
      featured: false,
    },
    {
      id: "experience-2",
      sectionId: "cv",
      kind: "experience",
      kicker: "2022 - 2024",
      title: "Desarrollador full-stack",
      meta: "Proyectos independientes",
      description:
        "IntegraciÃ³n de frontend, backend y automatizaciones para portales, paneles internos y webs de contenido.",
      href: null,
      tags: [],
      iconKey: "briefcase",
      order: 12,
      visibleFrom: null,
      visibleUntil: null,
      featured: false,
    },
    {
      id: "education-1",
      sectionId: "cv",
      kind: "education",
      kicker: "FormaciÃ³n",
      title: "Aprendizaje continuo en ingenierÃ­a web",
      meta: null,
      description:
        "Frontend moderno, backend Python, documentaciÃ³n tÃ©cnica y herramientas de IA aplicadas al desarrollo.",
      href: null,
      tags: [],
      iconKey: "rocket",
      order: 31,
      visibleFrom: null,
      visibleUntil: null,
      featured: false,
    },
    {
      id: "project-1",
      sectionId: "projects",
      kind: "project",
      kicker: "Marca personal",
      title: "Portal Fernando Luna",
      meta: "En construcciÃ³n",
      description: "Centro visual para CV, proyectos, publicaciones y documentaciÃ³n.",
      href: "https://fernandoluna.dev",
      tags: ["React", "Vite", "Python"],
      iconKey: "code",
      order: 1,
      visibleFrom: null,
      visibleUntil: null,
      featured: true,
    },
    {
      id: "project-2",
      sectionId: "projects",
      kind: "project",
      kicker: "Docs",
      title: "Biblioteca de documentaciÃ³n",
      meta: "DiseÃ±o",
      description: "Webs tÃ©cnicas organizadas por guÃ­as, decisiones y notas de implementaciÃ³n.",
      href: "https://docs.fernandoluna.dev",
      tags: ["Markdown", "Static site", "Search"],
      iconKey: "code",
      order: 2,
      visibleFrom: null,
      visibleUntil: null,
      featured: true,
    },
    {
      id: "project-3",
      sectionId: "projects",
      kind: "project",
      kicker: "Herramientas",
      title: "Laboratorio de automatizaciones",
      meta: "Activo",
      description: "PequeÃ±as utilidades para reducir trabajo repetitivo en proyectos personales.",
      href: "https://lab.fernandoluna.dev",
      tags: ["Python", "APIs", "Scripts"],
      iconKey: "code",
      order: 3,
      visibleFrom: null,
      visibleUntil: null,
      featured: false,
    },
    {
      id: "post-1",
      sectionId: "personal",
      kind: "post",
      kicker: "2026-05-19",
      title: "CÃ³mo estoy construyendo mi portal personal",
      meta: null,
      description:
        "Notas sobre arquitectura separada, diseÃ±o orbital e integraciÃ³n progresiva de contenido real.",
      href: "#",
      tags: [],
      iconKey: "user",
      order: 1,
      visibleFrom: null,
      visibleUntil: null,
      featured: false,
    },
    {
      id: "post-2",
      sectionId: "personal",
      kind: "post",
      kicker: "2026-05-10",
      title: "QuÃ© debe tener una buena documentaciÃ³n tÃ©cnica",
      meta: null,
      description: "Criterios prÃ¡cticos para que una guÃ­a sea fÃ¡cil de mantener y Ãºtil cuando hay prisa.",
      href: "#",
      tags: [],
      iconKey: "user",
      order: 2,
      visibleFrom: null,
      visibleUntil: null,
      featured: false,
    },
    {
      id: "focus-1",
      sectionId: "personal",
      kind: "focus",
      kicker: "Ahora mismo",
      title: "Portal Fernando Luna",
      meta: "En construcciÃ³n",
      description: "Centro visual para CV, proyectos, publicaciones y documentaciÃ³n.",
      href: "https://fernandoluna.dev",
      tags: ["React", "Vite", "Python"],
      iconKey: "layers",
      order: 21,
      visibleFrom: null,
      visibleUntil: null,
      featured: true,
    },
    {
      id: "focus-2",
      sectionId: "personal",
      kind: "focus",
      kicker: "Ahora mismo",
      title: "Biblioteca de documentaciÃ³n",
      meta: "DiseÃ±o",
      description: "Webs tÃ©cnicas organizadas por guÃ­as, decisiones y notas de implementaciÃ³n.",
      href: "https://docs.fernandoluna.dev",
      tags: ["Markdown", "Static site", "Search"],
      iconKey: "layers",
      order: 22,
      visibleFrom: null,
      visibleUntil: null,
      featured: true,
    },
    {
      id: "doc-1",
      sectionId: "docs",
      kind: "doc",
      kicker: "Documento",
      title: "GuÃ­as de desarrollo",
      meta: null,
      description: "Patrones, decisiones y comandos recurrentes para mis proyectos.",
      href: "https://docs.fernandoluna.dev/guias",
      tags: [],
      iconKey: "newspaper",
      order: 1,
      visibleFrom: null,
      visibleUntil: null,
      featured: false,
    },
    {
      id: "doc-2",
      sectionId: "docs",
      kind: "doc",
      kicker: "Documento",
      title: "BitÃ¡cora tÃ©cnica",
      meta: null,
      description: "Notas cortas sobre problemas resueltos y aprendizajes reutilizables.",
      href: "https://docs.fernandoluna.dev/bitacora",
      tags: [],
      iconKey: "newspaper",
      order: 2,
      visibleFrom: null,
      visibleUntil: null,
      featured: false,
    },
    {
      id: "doc-3",
      sectionId: "docs",
      kind: "doc",
      kicker: "Documento",
      title: "Recursos pÃºblicos",
      meta: null,
      description: "Plantillas, snippets y referencias que puedo compartir.",
      href: "https://docs.fernandoluna.dev/recursos",
      tags: [],
      iconKey: "newspaper",
      order: 3,
      visibleFrom: null,
      visibleUntil: null,
      featured: false,
    },
  ],
  momentaryTabs: [
    {
      id: "references",
      label: "Referencias",
      iconKey: "book",
      angle: -35,
      order: 10,
      visibleFrom: null,
      visibleUntil: null,
      enabled: true,
    },
    {
      id: "opportunities",
      label: "Oportunidades",
      iconKey: "rocket",
      angle: 55,
      order: 20,
      visibleFrom: null,
      visibleUntil: null,
      enabled: true,
    },
    {
      id: "events",
      label: "Eventos",
      iconKey: "newspaper",
      angle: 145,
      order: 30,
      visibleFrom: null,
      visibleUntil: null,
      enabled: true,
    },
    {
      id: "ideas",
      label: "Ideas",
      iconKey: "layers",
      angle: 235,
      order: 40,
      visibleFrom: null,
      visibleUntil: null,
      enabled: true,
    },
  ],
};
